// <auto-generated />
namespace BancedHealthyDiet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class seedrecipes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seedrecipes));
        
        string IMigrationMetadata.Id
        {
            get { return "202003142122092_seed recipes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
